config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root "songs#index"
  root "artists#index"

  resources :artists do
    resources :songs 
  end

  #resources :songs
  #resources :artists

 # get "songs" => "songs#index"
  #get "songs/new" => "songs#new", as: :new_song
  #get "songs/:id" => "songs#show", as: :song

  #post "songs" => "songs#create"

  #get 'songs/:id/edit' => 'songs#edit', as: :edit_song

  #patch "songs/:id" => "songs#update"

  #delete "songs/:id" => "songs#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	
	 validates :name, presence: true
  	 validates :name, uniqueness: true

     validates :image_url, length: { maximum: 255 }, allow_blank: true




	def self.order_by_name
    order(:name)
  	end

  	has_many :songs, dependent: :destroy


end

app/models/song.rb
class Song < ApplicationRecord

	validates :title, presence: true
  	validates :title, uniqueness: true

  	validates :album, presence: true
  	validates :album, uniqueness: true

  	validates :release_year, presence: true
  	validates :release_year, length: { maximum: 4 }, allow_blank: true

	def self.order_by_name
    order(:title)
  	end

    belongs_to :artist

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
    @artists = Artist.all
  	end

  	def show
    @artist = Artist.find(params[:id])
    #@song = @artist.songs.build
  	end

  	def new
    @artist = Artist.new
  	end

  	def create
   
    @artist = Artist.new(artist_params)

	    if @artist.save
	       redirect_to @artist
	    else
	       render 'new'
	    end
  	end

  	def edit
    @artist = Artist.find(params[:id])
  	end

  	def update
  		@artist = Artist.find(params[:id])

	    if @artist.update_attributes(artist_params)
	       redirect_to @artist
	    else
	       render 'edit'
	    end
  	end

  	def destroy
    @artist = Artist.find(params[:id])

    @artist.destroy

    redirect_to artists_path
  	end

  	private

  	def artist_params
    params.require(:artist).permit(:name, :image_url)
  	end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	def index
	  	
	    @songs = Artist.find(params[:artist_id]).songs
	 
    end

	#def show
    #@song = Song.find(song_params.merge(artist_id: params[:artist_id]))
    #end

	#def show
   # 	@song = @artist.songs.find(params[:id])
    #end


    def show
       @artist = Artist.find(params[:artist_id])
       @song = @artist.songs.find(params[:artist_id])
  	end

   # def new
	  	#artist = Artist.find(params[:artist_id])
	 # 	@song = Song.new
  	#end

  	def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.build
  	end

 	
  	def create
 	  @song = Song.create(song_params.merge(artist_id: params[:artist_id]))
      @song.save
      redirect_to artist_path(params[:artist_id])
    end




  	def edit
  	 @artist = Artist.find(params[:artist_id])
     @song = @artist.songs.find(params[:artist_id])
 	end

  	def update
  		@song = Song.find(params[:id])

	    #song_params = params.require(:song).permit(:title, :album, :release_year)


	    if @song.update_attributes(song_params)
	       redirect_to @song
	    else
	       render 'edit'
	    end
  	end

  	#def destroy
    #@song = Song.find(song_params.merge(artist_id: params[:artist_id]))

    #@song.save
   # redirect_to artist_path(params[:artist_id])
  	#end

def destroy
  @artist= Artist.find(params[:artist_id])
  @song = @artist.songs.find(params[:id])
  @song.destroy

  redirect_to artist_path(@artist)
end



  	private

  	def song_params
    params.require(:song).permit(:title, :album, :release_year, :artist_id)
  	end

end
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

	<ul>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <label>Photos</label>

<div class="form-group">
 <span class="btn btn-default">
    Upload Photos
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
</div>

  <%= f.submit (@artist.new_record? ? "Create" : "Update") %>




<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render "form" %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

<hr>

<%= link_to "[New Artist]", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit "Create" %>
<% end %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <%= image_tag @artist.image_url %>
</p>

<h4>List of Songs</h4>

<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
      <li><%= link_to song.title, artist_song_path(@artist, song) %></li>
    <% end %>
  </ul>
<% else %>
  <p>This artist doesn't have any songs.</p>
<% end %>

<hr>

<%= link_to "[Add Song to Artist]", new_artist_song_path(@artist.id) %>

<hr>

<%= link_to '[Edit Artist]', edit_artist_path(@artist) %> | <%= link_to "[Delete Artist]", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurifytwo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>


	<hr>

	<%= link_to "[All Artists]", root_path %>


  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f| %>

 <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :release_year %>
  <%= f.number_field :release_year %>

  <%= f.label :artist_id %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>

  <%= f.submit (@artist.new_record? ? "Create" : "Update") %>

<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render "form" %>

app/views/songs/index.html.erb
<h1>Artist: <h1>
<h2>Songs</h2>

<% @songs.each do |song| %>
  <p>Title: <%= song.title %></p>
  Album: <strong><%= song.album %></strong> Year: <strong><%= song.release_year %></strong></p>
  
<% end %>

<hr>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :release_year %>
  <%= f.number_field :release_year %>

  <%= f.submit "Create" %>
<% end %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

<p>Album: <%= @song.album %></p>
<p>Release year: <%= @song.release_year %></p>



<%= link_to "[Edit]", edit_artist_song_path(@artist, @song) %>
<%= link_to "[Delete]", artist_song_path(@song.id), method: :delete, data: { confirm: "Are you sure?" } %>
<hr>
<%= link_to "[Artist Songs]", artist_path(@song.id) %>